version: "3"
services:
    php_project:
        build: .
        ports:
            - "80:80"
        volumes:
            - ./www:/var/www/html
        networks:
            - app

    db_project:
        image: mysql:latest
        ports: 
            - "4400:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=fortesenhaquesentidonaofaz
            - MYSQL_DATABASE=projectdb
        networks:
            - app
networks:
    app: